[2022-12-19 17:16:29,306] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rates.dag4_process_rates manual__2022-12-19T17:16:24.414987+00:00 [queued]>
[2022-12-19 17:16:29,313] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rates.dag4_process_rates manual__2022-12-19T17:16:24.414987+00:00 [queued]>
[2022-12-19 17:16:29,313] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-19 17:16:29,313] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-19 17:16:29,313] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-19 17:16:29,325] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): dag4_process_rates> on 2022-12-19 17:16:24.414987+00:00
[2022-12-19 17:16:29,346] {standard_task_runner.py:52} INFO - Started process 239 to run task
[2022-12-19 17:16:29,349] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_rates', 'dag4_process_rates', 'manual__2022-12-19T17:16:24.414987+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/extract_data.py', '--cfg-path', '/tmp/tmppklgzak1', '--error-file', '/tmp/tmp2yum_zw0']
[2022-12-19 17:16:29,350] {standard_task_runner.py:80} INFO - Job 9: Subtask dag4_process_rates
[2022-12-19 17:16:29,391] {task_command.py:369} INFO - Running <TaskInstance: load_rates.dag4_process_rates manual__2022-12-19T17:16:24.414987+00:00 [running]> on host 9dc57627dd68
[2022-12-19 17:16:29,448] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_rates
AIRFLOW_CTX_TASK_ID=dag4_process_rates
AIRFLOW_CTX_EXECUTION_DATE=2022-12-19T17:16:24.414987+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-19T17:16:24.414987+00:00
[2022-12-19 17:16:29,471] {python.py:173} INFO - Done. Returned value was:           date symbol          rate
0   2022-01-01    AED      4.176782
1   2022-01-01    AFN    117.979297
2   2022-01-01    ALL    121.277018
3   2022-01-01    AMD    546.096265
4   2022-01-01    ANG      2.049808
..         ...    ...           ...
331 2022-01-02    YER    284.605769
332 2022-01-02    ZAR     18.156679
333 2022-01-02    ZMK  10236.956907
334 2022-01-02    ZMW     18.951110
335 2022-01-02    ZWL    366.206170

[336 rows x 3 columns]
[2022-12-19 17:16:29,487] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-12-19 17:16:29,487] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2380, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 197, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-12-19 17:16:29,496] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_rates, task_id=dag4_process_rates, execution_date=20221219T171624, start_date=20221219T171629, end_date=20221219T171629
[2022-12-19 17:16:29,505] {standard_task_runner.py:97} ERROR - Failed to execute job 9 for task dag4_process_rates (Object of type DataFrame is not JSON serializable; 239)
[2022-12-19 17:16:29,521] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-19 17:16:29,562] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
